### ISSUE TITLE
Notify on WinSparkle update closed

### ISSUE THREAD

**Issue by BrunoBibboVoicemod** [vslavik/winsparkle#271] opened 2024-05-10 16:03 UTC
Hi! I have a issue when closing the update dialog once download have finished. I give more context:

Our application do hide it's view if does found an update (we force the user to update to continue using the software). So if the user closes the update dialog when the package was already downloaded instead of click the "_install_" button, app will not be shown again as we don't receive any other event from WinSparkle.

When the updater finishes (closed by the user or installation starts) we would like run some checks after closing, but I don't see such behavior in this specific case above described.

We are using:
- WinSparkle V0.8.1
- Windows 11 Pro - Build 22631.3447

I took the liberty to check how was the "_quit_" behavior programmed and check how it would fit our needs. I found that in the `void UpdateDialog::OnClose(wxCloseEvent&)` method, at the end, there's an if preventing `ApplicationController::NotifyUpdateCancelled();` to be called if an update was already downloaded. I didn't want to mess with the current behavior of the library so I did just create a new event that will be executed always on WinSparkle update closed (yes, even when it closes successfully). This way I can suscribe to that behavior with a callback and do what I need to do without affecting the rest of usages.

I will submit a PR with the changes, what do you think?

Thanks in advance,
Bruno Bibbó

**Comment by vslavik** [comment] 2024-05-10 16:10
Duplicate of #127.

PRs are always welcome.

**Closed by vslavik** 2024-05-10 16:10 UTC

**Comment by BrunoBibboVoicemod** [comment] 2024-05-10 17:39
You're right, didn't saw the issue. PR submitted with the new callback method suggestion. Thanks!
