### ISSUE TITLE
Exception in win_sparkle_check_update_without_ui

### ISSUE THREAD

**Issue by ttgil** [vslavik/winsparkle#124] opened 2017-01-04 18:24 UTC
The only output I can see is:

Exception at 0x7689a832, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in WinSparkle!win_sparkle_check_update_without_ui
WinSparkle: The operation completed successfully.

The UI error message is not informative.  Is there a way to get more information about why the update is failing?  Using the latest 0.5.3 version but this problem manifested in 0.5.2 as well.

**Comment by vslavik** [comment] 2017-01-04 18:28
> Is there a way to get more information about why the update is failing?

Yes. It’s called “debugger”. As a developer, you should be familiar with them, so please use one to provide essential information like a backtrace etc. Failing that, please at the very least provide actual *reproducible* steps to see this, apparently, crash. As you can imagine, it’s somewhat hard to fix issues one can’t see.

**Comment by ttgil** [comment] 2017-01-05 17:10
Thanks, the issue was that we were rendering the xml from a web app, and neglected to include the content-length header.  In the code it treats content-length as an optional header, but it definitely didn't work without it and started working properly with it.

**Comment by vslavik** [comment] 2017-01-05 17:12
Again, please be a responsible user and a good Open Source citizen and give back a little by providing a reproducible test case. See http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by ttgil** [comment] 2017-01-05 17:17
Unfortunately, I won't be able to do that.  We use RoR, if that helps, it doesn't include the content-length header when rendering so you should be able to reproduce this easily by setting up a minimal server and printing static xml content.  You can also just state that content-length is required and not an optional header.

**Comment by vslavik** [comment] 2017-01-05 17:34
> Unfortunately, I won't be able to do that.

That’s not very helpful or nice. Using *years* of our hard work on WinSparkle to save some development time or asking for help with a bug, that you apparently can do, but helping even a little bit with said bug in return is something you can’t?

> We use RoR, if that helps

It doesn’t (whatever it even means). Reproducible test cases help. Pull requests with fixes help even more. If you *really* can’t provide a reproducible test case (as opposed to simply not *wanting* to), then a PR that doesn’t disclose whatever is preventing you is the way to go. Just please don’t be [a leech that takes and never gives back](http://www.infoworld.com/article/2632281/patents/the-fight-over-open-source--leeches-.html). Because that wouldn’t be cool.

> You can also just state that content-length is required and not an optional header.

I hold myself and my code to *slightly* higher standard than that. Under no circumstances is it acceptable to crash on *network input*. If that happens, it *must* be fixed.

**Comment by ttgil** [comment] 2017-01-05 17:48
RoR stands for Ruby on Rails.   I feel that I've helped narrow down the problem, and provided a solution to anyone who encounters it in the future.

**Comment by vslavik** [comment] 2017-01-05 19:04
> I feel that I've helped narrow down the problem

You stated some *hypothesis* that may or may not be true w/o backing it up with any evidence. As a matter of fact, no, that hypothesis is not true — unlikely you I actually tried under controlled conditions. Whatever you did, you *also* changed some other characteristics of the HTTP stream (such as buffering).

**Comment by vslavik** [comment] 2017-01-05 19:04
Closing as WORKSFORME due to uncooperative submitter.

**Closed by vslavik** 2017-01-05 19:04 UTC
