### ISSUE TITLE
Order of items seems to hide newest version.

### ISSUE THREAD

**Issue by Foaly** [vslavik/winsparkle#273] opened 2024-06-05 09:49 UTC
Hi there,

thank you very much for this great and handy library! I am using the current version 0.8.1 and I am observing a weird behaviour where I am not sure if it is intended or if I am doing anything wrong.

Consider the following appcast.xml setup:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Application Release</title>
    <link>https://website.com/downloads/</link>
    <description>The latest stable release.</description>
    <language>en</language>
    <item>
      <title>Version 0.21.1</title>
      <link>https://website.com/downloads/</link>
      <sparkle:version>0.21.1</sparkle:version>
      <pubDate>Tue, 03 Jun 2024 14:38:00 +0000</pubDate>
      <enclosure sparkle:os="windows"
                 url="https://website.com/download/win_installer_0.21.1.exe"
                 length="29052476"
                 type="application/octet-stream"/>
    </item>
    <item>
      <title>Version 0.20.1</title>
      <link>https://website.com/downloads/</link>
      <sparkle:version>0.20.1</sparkle:version>
      <pubDate>Tue, 02 Jun 2024 14:38:00 +0000</pubDate>
      <enclosure sparkle:os="windows"
                 url="https://website.com/download/win_installer_0.20.1.exe"
                 length="29051875"
                 type="application/octet-stream"/>
    </item>
    <item>
      <title>Version 0.19.1</title>
      <link>https://laseranimation.com/downloads/</link>
      <sparkle:version>0.19.1</sparkle:version>
      <pubDate>Tue, 01 Jun 2024 14:38:00 +0000</pubDate>
      <enclosure sparkle:os="windows"
                 url="https://website.com/download/win_installer_0.19.1.exe"
                 length="29052476"
                 type="application/octet-stream"/>
    </item>
  </channel>
</rss>
```
Meaning the order of the item's versions are:
* 0.21.1
* 0.20.1
* 0.19.1

Now if my application has the version number 0.20.0 and I call the feed above the update to 0.21.1 is correctly offered.

But if the order of items in the feed is:
* 0.20.1
* 0.21.1
* 0.19.1

Then, using version 0.20.0, I get offered 0.20.1 as the new available version. I would expect it to be the highest number in the feed.

The weird behaviour is even more pronounced, if I put the order like this:
* 0.19.1
* 0.20.1
* 0.21.1

Then no new version is offered, even though there are two new version in the feed.

Is this as intended or do I need to put some more properties/flags somewhere in the feed?

Thank you very much in advance!

**Comment by vslavik** [comment] 2024-06-12 13:36
Duplicate of https://github.com/vslavik/winsparkle/discussions/270#discussion-6558725

@zorgiepoo makes a killer point, PR would be most welcome.

**Closed** 2024-11-22 09:26 UTC

**Comment by Foaly** [comment] 2024-12-04 11:09
Thank you very much for fixing this issue and even making a new release! 🙂
