### ISSUE TITLE
example_psdk crash!!!

### ISSUE THREAD

**Issue by ehaerim** [vslavik/winsparkle#191] opened 2019-03-03 11:09 UTC
When I run example_psdk and press 'Install Update' button, it crashed:

    i = CRYPTO_add(&r->references, -1, CRYPTO_LOCK_DSA); => r seemed to have already been corrupted 

>	WinSparkle.dll!CRYPTO_add_lock(int * pointer=0x019ece80, int amount=0xffffffff, int type=0x00000008, const char * file=0x5e388520, int line=0x000000c4)  Line 629 + 0x3 bytes	C
 	WinSparkle.dll!DSA_free(dsa_st * r=0x019ece50)  Line 196 + 0x1e bytes	C
 	WinSparkle.dll!d2i_DSA_PUBKEY(dsa_st * * a=0x080df9b0, const unsigned char * * pp=0x080df820, long length=0x0000064a)  Line 280 + 0xb bytes	C
 	WinSparkle.dll!PEM_ASN1_read_bio(void * (void * *, const unsigned char * *, long)* d2i=0x5df20d40, const char * name=0x5e3883ac, bio_st * bp=0x009eb310, void * * x=0x080df9b0, int (char *, int, int, void *)* cb=0x00000000, void * u=0x00000000)  Line 81 + 0xf bytes	C
 	WinSparkle.dll!PEM_read_bio_DSA_PUBKEY(bio_st * bp=0x009eb310, dsa_st * * x=0x080df9b0, int (char *, int, int, void *)* cb=0x00000000, void * u=0x00000000)  Line 320 + 0x28 bytes	C
 	WinSparkle.dll!winsparkle::`anonymous namespace'::TinySSL::DSAPub::DSAPub(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & pem_key="-----BEGIN PUBLIC KEY-----
MIIGRjCCBDkGByqGSM44BAEwggQsAoICAQCS7frykSttT+BkjHTeY/BZMWN6Fxg3
nYg1gDHb+QxQElEikI/70f7oJ9f/UIijyFMZgUcdP2D28X2Wg/gFkvJkWric2HJL
/QiFEo0SWfcDu8ViDYnHqvGuZkQ1qZxs+cx6PCMU1Wej68JVj3jYhnL0j+hlUmI5
HodCMSjaIXA3MnX6VJ3qpG0dvz2E9dNP7SX52X0f1qJZU7LDRt+b+mhJifQM18Wq
pzH4GiJ1YwPMJ7jsz7kFx34qwa/WMvcpcpPvRZQnm5tNS6fW/VzWU9zoB9ANEWcE
7m0dsy2RPvPOu6DbHEK8HQngApIxshrX3QHBh/P1n48IEfctNMH3p9ZReGg7P5MU
McRemULs+uYxr846dNLp/SRplkOcoftCAdZpTdO+7kcZNpMxX8c0JuuOkI6+pNMn
iCw2kRmP7ktnPs1g19rbRB0G5wqXU3hoIVV8JJzgWMkj1sQdNWqvhdFuq8zzx5xQ
JlOHxDJIDINtZQc4p08oPcK5EFh2G0Zd3ykpn4TbKqBzbkFnqsSbwFeGKg+JJCT5
T9lommwz3Rtq0JxgJXizGA9OBLY49FYbPQBYUfOgakT6gJhgUoVqyrCj7OFLzH/p
O9ro+CcQgcsaaApHBLPgCX/kcBFDNuVuU/4Rwru2yi468hbMf7ySQJ8sLOPbYutZ
dKizdhJZ+qteGwIhAPVTS1dFaqLnENUXXC3Rf/9B9mZ1qd69pRaH16x94beXAoIC
ADtQsQV1F8jwYIQpkDIkypQFoMdXrkctnB+54SIw1PCE08t16MOI16SQhQ45bIY0
8wP6VXo/QtIswTG2OKiEAOprvhTheJR8/glXWqxAsbDhgcZ7OScsHbCywysLoCNh
FCbLzVt1WYnKxBdeOjdjPFq5gP/5CVgd7wdia3eqAz/tmgnttq0shVEP9hHh13jo
BKZrQcXap67Iluf1fcsmxHa2f4k2h2zz1AO7Zz/Fk6tNr7jGDLRmig4uii3x2tYz
wcmBT38Y0/9UWdyRTzZZ8ePiTxSJJhKRU8X8ARhvBjZ3teezKqD8vs7LThBOLODu
967p9Kf0q2pHNZyUuJFFlAeDp/H4/VJlIQwar8h7X1OWxxrA+b3NMuGTi+BMA6rS
7sEN6ZbO6/HJLeW3xtxsQ96miyQlyd68be9zbziGTKveT0ctdrztENtRi6wFf7/F
p7GUOMXBwkDluJw0fw8cy5t0PcIzzgjf7bSrbPfgDUDeaIHNKPjilCeWEaD3ahCO
pl3T0/E+RY+TEFkL0mhPvVHwxqaNSfrs977pEbxZJ+K9v68Rp6oUi3WmUQii6oqG
c/77JCoH8qVe8kgzj5BB6Z01oq+jZjrlqIofEsnxewi+Tm9RZ4affp9k7TtitUXp
YvxNXp/gOrReQV+1QLxLTiY4DjQ4UMi0nd4IeAhScWyDA4ICBQACggIAfngtVUTJ
r2sTChxOWLqHnIEi/Hbdm0wiTz5LXnvu/kRjXvG2YaRa2CYS1082jK7ywq2vf8g/
R0nMxWxpmB0+vW0NZY6hP3mnCaGn7v3W+i6tb0wUtdHPNRRGSj0zQJFJ7yA/nPLg
Aeku5wMlqUwIJvIRoPQKJ5eE/5dJrVz+wFcDsv3L3IrGR1S0rRbgoEAYpni5u7Bj
JaPJJ8pGVn0XqHPSyeSQh7So5cxE0YFYBUj/Bb+3etEcwv99pmsy7pWUUehofZt2
ZEBAdca6/AHIFbs5TqVMsVYXQha8/U3rENhzv+X0canxPeziu2n1Op5zIeUmQHqI
uu8w4YeEYo+cWO/jkssSAFvDAbtU2o0naMM+8deIscFkbqoRDu9iGL/X3O1g7Kb7
Df1fCnxSIon5LredUYqZekFAGPfdFPOfx243GAYEysSdmHwCd8muGQ1RvED63Hc6
rMEDBfwUjZMC4LhlMKICfcL5C6x0QaEtUhxKC)  Line 243 + 0x16 bytes	C++
 	WinSparkle.dll!winsparkle::`anonymous namespace'::TinySSL::VerifyDSASHA1Signature(const std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > & filename="C:\Users\ehaerim\AppData\Local\Temp\Update-4825f194-0ecd-4976-8b89-261519b4b9cd\Poedit-1.8.8-setup.exe", const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & signature="0D (u?먓搬"`U`潚?뙇?dB互?퉒? zT?Y$O짦?ep!쳳快i ㈏刃>癬W")  Line 192 + 0xe bytes	C++
 	WinSparkle.dll!winsparkle::SignatureVerifier::VerifyDSASHA1SignatureValid(const std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > & filename="C:\Users\ehaerim\AppData\Local\Temp\Update-4825f194-0ecd-4976-8b89-261519b4b9cd\Poedit-1.8.8-setup.exe", const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & signature_base64="MEQCICh10SofkNHa5iJgVWDi2O8RBYyN+nxkFEL7u/tBuWboAiB6VOV/WQMRJE+kRoICZXAhq5b24WkgqcDs0z7gyBkGVw==")  Line 301 + 0x4a bytes	C++
 	WinSparkle.dll!winsparkle::UpdateDownloader::Run()  Line 185 + 0x3b bytes	C++
 	WinSparkle.dll!winsparkle::Thread::ThreadEntryPoint(void * data=0x009ecb30)  Line 123	C++
 	WinSparkle.dll!_callthreadstartex()  Line 314 + 0xf bytes	C
 	WinSparkle.dll!_threadstartex(void * ptd=0x009eaeb0)  Line 297	C
 	kernel32.dll!764e343d() 	
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	
 	ntdll.dll!76ed9802() 	
 	ntdll.dll!76ed97d5()

**Comment by vslavik** [comment] 2019-03-03 11:17
You're a developer; surely you're competent enough to be capable of using a debugger. So, please do. Please also [read this](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) (should be nothing new for a developer) and proceed accordingly with a description and reproduction steps. Either would be more productive than shouting with an overload of exclamation points.

It goes without saying that this does not happen here and whatever the issue is is in something you don't disclose (your OS, version, modifications you have made, the way you compiled etc.).

**Comment by vslavik** [comment] 2019-03-19 08:26
Closing because OP ignores requests for clarification; probably bogus.

**Closed by vslavik** 2019-03-19 08:26 UTC
