### ISSUE TITLE
Crash when running releases above 0.5 under Windows XP

### ISSUE THREAD

**Issue by barnacleboy** [vslavik/winsparkle#122] opened 2016-11-11 23:18 UTC
Hi!

First, thanks for "porting" Sparkle to Windows. WinSparkle worked flawless so far for me.

I'm experiencing crashes when using the latest releases of WinSparkle. Version 0.5 works fine, but the newer version keep crashing in 32 bit XP. Since I'm calling the DLL from .NET, that's all I've got:
Type: System.DllNotFoundException
Message: Unable to load DLL 'WinSparkle.dll': Unzulässiger Zugriff auf einen Speicherbereich. (Exception from HRESULT: 0x800703E6)

Replacing the DLL with the release 0.5 DLL resolves the issue.

Thank you for your help!

Cheers
P

**Comment by vslavik** [comment] 2016-11-11 23:31
You're a developer, so can you please do what developers do -- investigate? Use Dependency Walker to find out *what* DLL this is about - kind of important. Please also be more specific about which releases you tried. If possible, try git bisecting.

**Comment by barnacleboy** [comment] 2016-11-11 23:40
Sure. I will look into it asap. Thought there were bigger changes that could cause this issue... 

Looks not like a missing DLL - the exception translates to "Invalid access to memory location".

**Comment by vslavik** [comment] 2016-11-12 00:06
> Thought there were bigger changes that could cause this issue...

Not intentional ones, no.

**Comment by vslavik** [comment] 2016-11-13 18:17
I have just confirmed that the master, compiled with VS2015 (which I used for released as well) works just fine on Windows XP SP3 here.

**Comment by ZhouBox** [comment] 2016-12-30 08:33
hi,when i use in xp,notify no Internet

**Comment by vslavik** [comment] 2016-12-30 08:36
Closing as WORKSFORME  due to the submitter not providing promised information.

**Closed by vslavik** 2016-12-30 08:36 UTC
