### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by kkuday** [vslavik/winsparkle#52] opened 2015-02-21 07:07 UTC
I used win sparkle for update mechanism in my windows application it works fine for me .  I am  facing a problem with  updated exe which pops up and asking for installation, here I want  to  know how to install exe silently without any user interaction.  Is this possible with  current version  of win sparkle ? if it is possible, please let me know in detail   how it works . I  struck at this point for a while.  please do help me .

**Comment by TingPing** [comment] 2015-02-21 07:21
Duplicate of #21

**Closed** 2015-02-27 11:49 UTC
