### ISSUE TITLE
Webbrowser display error

### ISSUE THREAD

**Issue by shelllet** [vslavik/winsparkle#226] opened 2021-03-09 08:57 UTC
webbrowser don't embed in update window.

![image](https://user-images.githubusercontent.com/16729017/110444525-18211c80-80f8-11eb-8139-77a2d2c221b1.png)

os: win10 pro 20 h2
dell notebook 4k display monitor

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.VCRTForwarders.140" version="1.0.7" targetFramework="native" />
  <package id="Microsoft.Windows.CppWinRT" version="2.0.210304.5" targetFramework="native" />
  <package id="Microsoft.WinUI" version="3.0.0-preview4.210210.4" targetFramework="native" />
  <package id="Win2D.uwp" version="1.25.0" targetFramework="native" />
  <package id="WinSparkle" version="0.8.0-beta2" targetFramework="native" />
</packages>
```

**Comment by vslavik** [comment] 2021-03-09 13:16
Please read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html and *after* having done so, provide actual reproduction instructions — ideally in the form of a patch against the sample included with WinSparkle. If you can't reproduce it in the example, it would be an indication that the problem lies in your code in something specific you do with WinSparkle, and in that case isolating the cause and describing it well is doubly important.

**Comment by shelllet** [comment] 2021-03-10 00:57
sorry , i have no time to read . I refer to  winsparkle examples  but  in my winui3 preview4 c++ desktop. 
webbrowser is deprecated , winui3 provide webview2 control.
i will wait winui3 production-ready release. and test. if still like this , i will give up using.

**Comment by vslavik** [comment] 2021-03-10 06:56
> sorry , i have no time to read 

You seem to have gotten a lot about Open Source wrong. You're using, for free, a lot of work of WinSparkle contributors, to make your life easier. You're evidently feeling entitled to get free support too, and you can't even be bothered to do non-crappy job of *describing* the issue? 

That selfish attitude is not welcome here.

Closing as presumed bogus.

**Closed by vslavik** 2021-03-10 06:56 UTC
