### ISSUE TITLE
App stays and not quit, when we deal with "Check Automatically".

### ISSUE THREAD

**Issue by kenjiuno** [vslavik/winsparkle#44] opened 2015-01-19 03:05 UTC
Hi.

App keep staying when I do like the following instructions:

1. Launch app. See [Window1]
2. [Window2] appears.
3. Click [Btn1].
4. [Window3] appears.
5. Click either [Btn2] or [Btn3].
6. Both [Window2] and [Window3] disappear.
7. Close [Window1]
8. [Window1] disappears, but app won't quit.

![updatescreens](https://cloud.githubusercontent.com/assets/5955540/5795419/14f7e352-9fd3-11e4-97f7-9f8a1b52846a.png)

**Comment by kenjiuno** [comment] 2015-01-19 04:30
Hi.

I have posted a pull request to fix this issue, though I'm not sure if it is good solution.

Thanks
kenji uno

**Comment by kenjiuno** [comment] 2015-01-19 04:36
Hi.

If you try to show CheckUpdate dialog again in example_psdk.exe:
Delete [CheckForUpdates] value from the registry key [HKEY_CURRENT_USER\Software\winsparkle.org\WinSparkle Example App\WinSparkle].

**Comment by vslavik** [comment] 2015-01-19 07:45
Did you try with the very latest sources (it's always worth doing)? Specifically, with sources that include 8a440b6? I'm almost sure this is a duplicate of #42 and was just fixed 3 days ago. Could you please check if that's the case?

**Comment by kenjiuno** [comment] 2015-01-19 08:47
Hi.

> Did you try with the very latest sources

Yes, I have tried and worked on latest master 2ee16f6c1126138c30c3bf0a4a2bb2a64d9c8c78.

The fix 8a440b610b376a9b671d6534bd53b96d8a38e576 is included and it didn't fix my problem.

My issue is about "dialog's parent window":
- [Window2] owns [Window3], because wxDIALOG_NO_PARENT isn't specified. I don't know whether this is specification/bug of wxWidgets or not. You can check it by using Spy++.
- If you close [Window2] by selecting one of [Btn2][Btn3], [Window3] is destroyed. It seems that it is done without required post processing of wxWidgets. It means that wxWidgets treats [Window3] is still alive, so app won't quit, because UI thread cannot be terminated.

**Comment by vslavik** [comment] 2015-01-19 09:11
> My issue is about "dialog's parent window":

(Your issue was *with application not terminating*. Nowhere in the description was it apparent that it could be related to parent-child relationship, so the assumption that it was related to 8a440b6 was IMHO a reasonable one.)

Thanks for the follow-up explanation! This parentship relationship between the windows would be correct without `wxDIALOG_NO_PARENT` *if* [Window2] was created first; it's highly surprising to me that wx would reparent later, when the dialog is already being shown modally. That's a *very* valuable observation and makes the reason for #45 much cleaner, thanks a lot for that. (It's exactly the kind of description that would be great to have in the commit message itself, too.)

I still don't understand how could 8a440b6 not work, but that's a problem with me, not this issue and PR — I must still be missing something :(

**Closed** 2015-01-19 14:25 UTC

**Comment by kenjiuno** [comment] 2015-01-21 07:34
Hi.

Sorry, I have found a side effect brought by this patch!

**Comment by kenjiuno** [comment] 2015-01-21 07:51
Hi.

My mention "a side effect" at the prior post is by my misunderstanding. Sorry!
